export const GET_GIST_FOR_USERS_REQUEST = "GET_GIST_FOR_USERS_REQUEST";
export const GET_GIST_FOR_USERS_SUCCESS = "GET_GIST_FOR_USERS_SUCCESS";
export const GET_GIST_FOR_USERS_FAILURE = "GET_GIST_FOR_USERS_FAILURE";
export const GET_GIST_PUBLIC_REQUEST = "GET_GIST_PUBLIC_REQUEST";
export const GET_GIST_PUBLIC_SUCCESS = "GET_GIST_PUBLIC_SUCCESS";
export const GET_GIST_PUBLIC_FAILURE = "GET_GIST_PUBLIC_FAILURE";
export const CLEAR_ALL_STATES = "CLEAR_ALL_STATES";
